language: android
android:
  components:
    - build-tools-19.0.3
    - android-19
    - sysimg-19
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

before_install:
  - mvn install:install-file -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.0.1  -Dpackaging=jar -Dfile="$ANDROID_HOME/extras/android/support/v4/android-support-v4.jar"

script:
  - mvn clean install -e -X -Plinux
notifications:
  email:
    - hijack3703@gmail.com