language: android
android:
  components:
    - build-tools-21.1.1
    - android-21
    - sys-img-armeabi-v7a-android-21
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.*intel.+'

before_install:
  #- mvn install:install-file -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.0.1  -Dpackaging=jar -Dfile="$ANDROID_HOME/extras/android/m2repository/com/android/support/support-v4/19.0.1/support-v4-19.0.1.jar"
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script:
  - gradle installDebug --stacktrace
notifications:
  email:
    - hijack3703@gmail.com