language: android
android:
  components:
    - build-tools-21.1.1
    - android-19
    - sysimg-19
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - '.*intel.+'

before_install:
  #- mvn install:install-file -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.0.1  -Dpackaging=jar -Dfile="$ANDROID_HOME/extras/android/m2repository/com/android/support/support-v4/19.0.1/support-v4-19.0.1.jar"

script:
  - gradle installDebug --stacktrace
notifications:
  email:
    - hijack3703@gmail.com